name: "This workflow belongs to todoMicroApp"

on: 
  push:
    branch:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: spy
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: cdb3e7ef-de15-4ab2-814a-3d8589fb4afc
        tenant-id: 06af33d0-e479-4edf-a312-5cc8f0113164
        subscription-id: b3e9b690-1f69-4cae-899a-6a1c65b2db91

    - name: Terraform Init
      id: init
      working-directory: environment/dev
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      working-directory: environment/dev
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: environment/dev
      run: terraform plan -no-color -input=false

  terraform-apply:
    runs-on: spy
    needs: terraform-init-plan
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: cdb3e7ef-de15-4ab2-814a-3d8589fb4afc
        tenant-id: 06af33d0-e479-4edf-a312-5cc8f0113164
        subscription-id: b3e9b690-1f69-4cae-899a-6a1c65b2db91

    - name: Terraform Init
      id: init
      working-directory: environment/dev
      run: terraform init -input=false    

    - name: Terraform Apply
      id: apply
      working-directory: environment/dev
      run: terraform apply --auto-approve
    
  


      
       
